version: '3.8'

services:
  backend:
    build: .
    container_name: consumer-go
    environment:
      NOME_FILA: exames-pendentes
      IP_FILA: 192.168.207.165
      USUARIO_FILA: guest
      PASS_FILA: guest
      PORTA_FILA: 5672
      SENHA_APP_GMAIL: "senha"
      FROM_APP_GMAIL: "email"
      
    ports:
      - "8080:8080"
     
     
