services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json
    environment:
      RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json